---
- hosts: databaseservers 
  become: yes
  gather_facts: true
  tasks:
     - name: Install packages
       yum:
         name: "{{ item }}"
         state: present
#       with_items:
       loop:
         - curl
         - finger
         - wget
         - httpd
         - ntp 
