---
- hosts: all
  become: true
  gather_facts: yes
  vars:
    user_name: lanray2024
    group_name: devops
  vars_files:
    - variables.yml
    
  tasks:
    - name: Check the time
      command: date
      when: ansible_distribution == "lanray" or ansible_processor_nproc == 2
    - name: create user serge
      user:
         name: "{{user_name}}"
         comment: Lanray Admin
    - name: create group
      group:
         name: "{{group_name}}"
         state: present
    - name: Install package
      package:
        name: "{{pkg_name}}"
        state: present
